apiVersion: v2
description: Deploy components and dependencies of azure-service-operator
home: https://github.com/Azure/azure-service-operator/v2
name: azure-service-operator
sources:
- https://github.com/Azure/azure-service-operator/v2
version: 2.3.0
