apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: azdevspace
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_SERVICE_HOST
          value: redis
        - name: REDIS_SERVICE_PORT
          value: "6379"
        - name: NODE_ENV
          value: production
        - name: AZURE_STORAGE_ACCOUNT
          value: sportfs
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-account-secret
              key: azurestorageaccountkey
        - name: AZURE_SHARE_NAME
          value: sportshare
        - name: MONGODB_URL # Add this environment variable
          valueFrom:
            secretKeyRef:
              name: my-cluster-secrets
              key: MONGODB_URL # Use the correct key name
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      imagePullSecrets:
      - name: my-registry-secret
      volumes:
      - name: redis-file
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: azdevspace
spec:
  minAvailable: 2 # Set the minimum available pods to 2 (to allow 1 disruption)
  selector:
    matchLabels:
      app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: azdevspace
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
